SRC_DIR = src
INC_DIR = include

# Lista de arquivos fonte
SRC = $(SRC_DIR)/maps_read.c \
      $(SRC_DIR)/main.c \
	  $(SRC_DIR)/maps_valid.c \
	  $(SRC_DIR)/utils.c


# Lista de objetos a serem gerados
OBJS = $(SRC:$(SRC_DIR)/%.c=$(SRC_DIR)/%.o)

# Compilador e flags
CC = cc
CFLAGS = -Wall -Werror -Wextra
MLX_DIR = library/minilibx-linux

NAME = so_long

# Diretórios da libft
LIBFT_DIR = library/libft
LIBFT = $(LIBFT_DIR)/libft.a

# Flags de link
LDFLAGS = -L $(LIBFT_DIR) -lft -L$(MLX_DIR) -lmlx -lX11 -lXext -lm

# Regra principal
all: $(NAME)

# Compilar o jogo
$(NAME): $(OBJS) $(LIBFT)
	@$(MAKE) -C $(LIBFT_DIR) - # Garantir que a libft seja compilada
	$(CC) $(CFLAGS) -I $(INC_DIR) -I $(MLX_DIR) -o $(NAME) $(OBJS) $(LIBFT) $(LDFLAGS)

# Limpeza
clean:
	rm -rf $(OBJS)
	$(MAKE) -C $(LIBFT_DIR) clean

fclean: clean
	rm -rf $(NAME)
	$(MAKE) -C $(LIBFT_DIR) fclean

# Recompilar tudo
re: fclean all

valgrind: $(NAME)
	valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./$(NAME)

.PHONY: all clean fclean re